
export type Language = 'de' | 'en' | 'fr' | 'ceb' | 'tl';

export const translations = {
  de: {
    dashboard: "Dashboard",
    learn: "Lernen",
    vocabulary: "Vokabeln",
    settings: "Einstellungen",
    themes: "Themen",
    progress_overview: "Dein Lernfortschritt auf einen Blick.",
    ready_to_learn: "Bereit",
    learned: "Gelernt",
    archive: "Archiv",
    errors: "Fehler",
    daily_goal_vocab: "Tagesziel: Vokabeln",
    daily_goal_time: "Tagesziel: Zeit",
    goal_reached: "Ziel erreicht! 🎉",
    minutes: "Minuten",
    vocab_per_min: "Vok / Min",
    correct_per_min: "Richtig / Min",
    active_words: "Aktive Wörter",
    what_to_learn: "Was möchtest du heute lernen?",
    start_session: "Session starten",
    cancel: "Abbrechen",
    save: "Speichern",
    language: "Sprache",
    ui_language: "App-Sprache",
    select_language: "Wähle die Sprache der Benutzeroberfläche",
    german: "Deutsch",
    english: "Englisch",
    french: "Französisch",
    bisaya: "Bisaya",
    tagalog: "Tagalog",
    session_finished: "Session beendet!",
    back_to_dashboard: "Zurück zum Dashboard",
    no_vocab_available: "Keine Vokabeln verfügbar",
    session_prep: "Session Vorbereiten",
    results: "Ergebnis",
    duration: "Dauer",
    cards_processed: "Karten erfolgreich bearbeitet",
    manage_vocab_lists: "Vokabel-Listen",
    data_management: "Vokabelverwaltung",
    learning_intervals: "Lernintervalle",
    feedback_support: "Feedback & Support",
    sources: "Quellen",
    settings_and_data: "Einstellungen & Daten",
    answer: "Antwort",
    show_answer: "Antwort zeigen",
    word_type: "Wortart",
    article: "Artikel",
    singular: "Singular",
    plural: "Plural",
    auxiliary_verb: "Hilfsverb",
    past_participle: "Partizip II",
    present_tense: "Präsens (er/sie/es)",
    past_tense: "Präteritum (er/sie/es)",
    example_sentence: "Beispielsatz",
    synonyms: "Synonyme",
    antonyms: "Gegenteil",
    notes: "Anmerkungen",
    undo_last_card: "Letzte Karte (Undo)",
    end_session_and_save: "Session beenden & Speichern",
    session_progress_error: "Session-Fortschritt konnte nicht geladen werden.",
    session_progress_error_hint: "Dies kann bei sehr schnellen Eingaben passieren.",
    progress: "Fortschritt",
    time_remaining: "Verbleibende Zeit",
    de_en: "Deutsch → Englisch",
    en_de: "Englisch → Deutsch",
    content_balance: "Inhalt & Balance",
    vocab_lists: "Vokabellisten",
    clear_all: "Alle löschen",
    all_lists: "Alle Listen",
    select_lists_hint: "Wähle eine oder mehrere Listen zum Lernen aus.",
    books_collections: "Bücher & Sammlungen",
    individual_lists: "Einzelne Listen",
    sequential_learning_hint: "Lerne die Kapitel eines Buches nacheinander.",
    word_mix: "Mix & Balance",
    new_words_count: "Anzahl neue Wörter",
    new_words_hint: "Diese Wörter werden vor den Wiederholungen gelernt.",
    more_review: "Mehr Wiederholung",
    more_new: "Mehr Neue Wörter",
    learning_direction: "Lern-Richtung",
    de_to_en: "Deutsch zu Englisch",
    en_to_de: "Englisch zu Deutsch",
    mixed: "Gemischt",
    random_change: "Zufälliger Wechsel",
    session_goal: "Session-Ziel",
    how_to_measure: "Wie möchtest du messen?",
    measure_hint: "Wähle zwischen einer festen Anzahl oder einer Zeitspanne.",
    card_count: "Anzahl Karten",
    time_limit: "Zeitlimit",
    vocab_count: "Vokabeln",
    recommended: "Empfohlen",
    pro_tip: "Profi-Tipp:",
    manage_themes: "Themen verwalten",
    select_theme: "Thema wählen",
    all_themes: "Alle Themen",
    new: "Neu",
    box_disclaimer_text: "Da du noch am Anfang stehst oder deine Boxen leer sind, füllen wir die Session mit neuen Vokabeln auf. Sobald mehr Vokabeln in Box 2 und höher sind, priorisieren wir automatisch die Wiederholungen für maximalen Lernerfolg.",
    learning_activity: "Lernaktivität (7 Tage)",
    box_distribution: "Box Verteilung",
    correct: "Richtig",
    vocab_calculator: "Vokabel-Rechner",
    plan_your_journey: "Plane deinen Erfolg",
    exam_format: "Prüfungsformat",
    start_date: "Startdatum",
    end_date: "Prüfungsdatum",
    current_level: "Aktuelles Level",
    target_level: "Ziel-Level",
    custom_vocab_count: "Eigene Wortanzahl",
    daily_requirement: "Täglicher Bedarf",
    to_reach_your_goal_learn: "Um dein Ziel zu erreichen, lerne täglich:",
    new_words: "neue Wörter",
    total_vocab_target: "Gesamtziel",
    current_vocab_count: "Bereits bekannt",
    vocabularies: "Vokabeln",
    learn_from_lists: "Aus Listen & Büchern lernen",
    base_vocabulary: "Basis-Vokabelschatz nutzen",
    all_books: "Alle Bücher",
    show_details: "Details einblenden",
    hide_details: "Details ausblenden",
    privacy_policy: "Datenschutzerklärung",
    privacy_at_maylang: "Datenschutz bei Maylang",
    privacy_intro: "Deine Daten gehören dir. Maylang wurde entwickelt, um dir beim Sprachenlernen zu helfen, ohne deine Privatsphäre zu beeinträchtigen.",
    privacy_what_save_title: "1. Was wir speichern",
    privacy_what_save_desc: "Maylang speichert ausschließlich Daten, die für deinen Lernfortschritt notwendig sind. Dazu gehören:",
    privacy_item_progress: "Deine Vokabellisten und dein Lernstatus (Boxen, Fehlerzahlen).",
    privacy_item_history: "Dein Lernverlauf und Statistiken (Zeitpunkt und Ergebnis von Abfragen).",
    privacy_item_settings: "Deine App-Einstellungen.",
    privacy_item_google: "Deine Google-ID (nur bei Cloud-Sync), um Daten dem Konto zuzuordnen.",
    privacy_what_save_footer: "Es werden keine weiteren persönlichen Daten wie Name, Adresse oder Telefonnummer erhoben.",
    privacy_location_title: "2. Speicherort & Sicherheit",
    privacy_location_desc: "Deine Daten werden primär lokal in deinem Browser gespeichert. Bei Anmeldung werden verschlüsselte Snapshots in Google Firebase Storage (Serverstandort USA) gesichert.",
    privacy_duration_title: "3. Dauer der Speicherung & Löschung",
    privacy_duration_desc: "Wir speichern Daten nur so lange, wie du einen Account hast. Löschen ist jederzeit über die Einstellungen möglich.",
    privacy_third_party_title: "4. Weitergabe an Dritte",
    privacy_third_party_desc: "Maylang gibt niemals Daten an Dritte weiter. Kein Tracking zu Werbezwecken.",
    privacy_contact_title: "5. Kontakt",
    privacy_contact_desc: "Bei Fragen kannst du uns über Feedback oder E-Mail kontaktieren.",
    privacy_updated: "Stand: Mai 2026",
  },
  en: {
    dashboard: "Dashboard",
    learn: "Learn",
    vocabulary: "Vocabulary",
    settings: "Settings",
    themes: "Themes",
    progress_overview: "Your learning progress at a glance.",
    ready_to_learn: "Ready",
    learned: "Learned",
    archive: "Archive",
    errors: "Errors",
    daily_goal_vocab: "Daily Goal: Words",
    daily_goal_time: "Daily Goal: Time",
    goal_reached: "Goal reached! 🎉",
    minutes: "Minutes",
    vocab_per_min: "Words / Min",
    correct_per_min: "Correct / Min",
    active_words: "Active Words",
    what_to_learn: "What do you want to learn today?",
    start_session: "Start Session",
    cancel: "Cancel",
    save: "Save",
    language: "Language",
    ui_language: "App Language",
    select_language: "Choose the interface language",
    german: "German",
    english: "English",
    french: "French",
    bisaya: "Bisaya",
    tagalog: "Tagalog",
    session_finished: "Session finished!",
    back_to_dashboard: "Back to Dashboard",
    no_vocab_available: "No vocabulary available",
    session_prep: "Prepare Session",
    results: "Result",
    duration: "Duration",
    cards_processed: "cards successfully processed",
    manage_vocab_lists: "Vocabulary Lists",
    data_management: "Vocabulary Management",
    learning_intervals: "Learning Intervals",
    feedback_support: "Feedback & Support",
    sources: "Sources",
    settings_and_data: "Settings & Data",
    answer: "Answer",
    show_answer: "Show Answer",
    word_type: "Word Type",
    article: "Article",
    singular: "Singular",
    plural: "Plural",
    auxiliary_verb: "Auxiliary Verb",
    past_participle: "Past Participle",
    present_tense: "Present (he/she/it)",
    past_tense: "Past (he/she/it)",
    example_sentence: "Example Sentence",
    synonyms: "Synonyms",
    antonyms: "Antonyms",
    notes: "Notes",
    undo_last_card: "Undo Last Card",
    end_session_and_save: "End Session & Save",
    session_progress_error: "Session progress could not be loaded.",
    session_progress_error_hint: "This can happen with very fast inputs.",
    progress: "Progress",
    time_remaining: "Time Remaining",
    de_en: "German → English",
    en_de: "English → German",
    content_balance: "Content & Balance",
    vocab_lists: "Vocabulary Lists",
    clear_all: "Clear All",
    all_lists: "All Lists",
    select_lists_hint: "Select one or more lists to learn from.",
    word_mix: "Word Mix",
    more_review: "More Review",
    more_new: "More New Words",
    learning_direction: "Learning Direction",
    de_to_en: "German to English",
    en_to_de: "English to German",
    mixed: "Mixed",
    random_change: "Random Change",
    session_goal: "Session Goal",
    how_to_measure: "How do you want to measure?",
    measure_hint: "Choose between a fixed count or a time span.",
    card_count: "Card Count",
    time_limit: "Time Limit",
    vocab_count: "Words",
    recommended: "Recommended",
    pro_tip: "Pro Tip:",
    manage_themes: "Manage Themes",
    select_theme: "Select Theme",
    all_themes: "All Themes",
    new: "New",
    box_disclaimer_text: "Since you are just starting out or your boxes are empty, we are filling the session with new vocabulary. As soon as more vocabulary is in Box 2 and higher, we automatically prioritize reviews for maximum learning success.",
    learning_activity: "Learning Activity (7 Days)",
    box_distribution: "Box Distribution",
    correct: "Correct",
    vocab_calculator: "Vocab Calculator",
    plan_your_journey: "Plan Your Success",
    exam_format: "Exam Format",
    start_date: "Start Date",
    end_date: "Exam Date",
    current_level: "Current Level",
    target_level: "Target Level",
    custom_vocab_count: "Custom Word Count",
    daily_requirement: "Daily Requirement",
    to_reach_your_goal_learn: "To reach your goal, learn daily:",
    new_words: "new words",
    total_vocab_target: "Total Target",
    current_vocab_count: "Already Known",
    vocabularies: "Vocabularies",
    learn_from_lists: "Learn from lists & books",
    base_vocabulary: "Use base vocabulary",
    all_books: "All Books",
    show_details: "Show details",
    hide_details: "Hide details",
    privacy_policy: "Privacy Policy",
    privacy_at_maylang: "Privacy at Maylang",
    privacy_intro: "Your data belongs to you. Maylang was developed to help you learn languages without compromising your privacy.",
    privacy_what_save_title: "1. What we store",
    privacy_what_save_desc: "Maylang stores only data that is necessary for your learning progress. This includes:",
    privacy_item_progress: "Your vocabulary lists and learning status (boxes, error counts).",
    privacy_item_history: "Your learning history and statistics (timing and result of queries).",
    privacy_item_settings: "Your app settings.",
    privacy_item_google: "Your Google ID (only with cloud sync) to link data to your account.",
    privacy_what_save_footer: "No other personal data such as name, address, or phone number is collected.",
    privacy_location_title: "2. Storage Location & Security",
    privacy_location_desc: "Your data is primarily stored locally in your browser. When logged in, encrypted snapshots are saved in Google Firebase Storage (Server location: USA).",
    privacy_duration_title: "3. Duration of Storage & Deletion",
    privacy_duration_desc: "We store your data only as long as you have an account. Deletion is possible at any time via the settings.",
    privacy_third_party_title: "4. Disclosure to Third Parties",
    privacy_third_party_desc: "Maylang never passes data to third parties. No tracking for advertising purposes.",
    privacy_contact_title: "5. Contact",
    privacy_contact_desc: "If you have questions, you can contact us via feedback or email.",
    privacy_updated: "Last updated: May 2026",
  },
  fr: {
    dashboard: "Tableau de bord",
    learn: "Apprendre",
    vocabulary: "Vocabulaire",
    settings: "Paramètres",
    themes: "Thèmes",
    progress_overview: "Votre progression en un coup d'œil.",
    ready_to_learn: "Prêt",
    learned: "Appris",
    archive: "Archives",
    errors: "Erreurs",
    daily_goal_vocab: "Objectif : Mots",
    daily_goal_time: "Objectif : Temps",
    goal_reached: "Objectif atteint ! 🎉",
    minutes: "Minutes",
    vocab_per_min: "Mots / Min",
    correct_per_min: "Correct / Min",
    active_words: "Mots actifs",
    what_to_learn: "Qu'est-ce que tu veux apprendre aujourd'hui ?",
    start_session: "Démarrer la session",
    cancel: "Annuler",
    save: "Enregistrer",
    language: "Langue",
    ui_language: "Langue de l'application",
    select_language: "Choisissez la langue de l'interface",
    german: "Allemand",
    english: "Anglais",
    french: "Français",
    bisaya: "Bisaya",
    tagalog: "Tagalog",
    session_finished: "Session terminée !",
    back_to_dashboard: "Retour au tableau de bord",
    no_vocab_available: "Aucun vocabulaire disponible",
    session_prep: "Préparer la session",
    results: "Résultat",
    duration: "Durée",
    cards_processed: "cartes traitées avec succès",
    manage_vocab_lists: "Gérer les listes de vocabulaire",
    data_management: "Gestion des données",
    learning_intervals: "Intervalles d'apprentissage",
    feedback_support: "Feedback & Support",
    sources: "Sources",
    settings_and_data: "Paramètres & Données",
    answer: "Réponse",
    show_answer: "Afficher la réponse",
    word_type: "Type de mot",
    article: "Article",
    singular: "Singulier",
    plural: "Pluriel",
    auxiliary_verb: "Verbe auxiliaire",
    past_participle: "Participe passé",
    present_tense: "Présent (il/elle)",
    past_tense: "Passé (il/elle)",
    example_sentence: "Exemple de phrase",
    synonyms: "Synonymes",
    antonyms: "Antonymes",
    notes: "Notes",
    undo_last_card: "Annuler la dernière carte",
    end_session_and_save: "Terminer la session & Enregistrer",
    session_progress_error: "Impossible de charger la progression de la session.",
    session_progress_error_hint: "Cela peut arriver avec des entrées très rapides.",
    progress: "Progression",
    time_remaining: "Temps restant",
    de_en: "Allemand → Anglais",
    en_de: "Anglais → Allemand",
    content_balance: "Contenu & Équilibre",
    vocab_lists: "Listes de vocabulaire",
    clear_all: "Tout effacer",
    all_lists: "Toutes les listes",
    select_lists_hint: "Sélectionnez une ou plusieurs listes pour apprendre.",
    word_mix: "Mélange de mots",
    more_review: "Plus de révision",
    more_new: "Plus de nouveaux mots",
    learning_direction: "Direction d'apprentissage",
    de_to_en: "Allemand vers Anglais",
    en_to_de: "Anglais vers Allemand",
    mixed: "Mixte",
    random_change: "Changement aléatoire",
    session_goal: "Objectif de la session",
    how_to_measure: "Comment voulez-vous mesurer ?",
    measure_hint: "Choisissez entre un nombre fixe ou une durée.",
    card_count: "Nombre de cartes",
    time_limit: "Limite de temps",
    vocab_count: "Mots",
    recommended: "Recommandé",
    pro_tip: "Conseil de pro :",
    manage_themes: "Gérer les thèmes",
    select_theme: "Sélectionner le thème",
    all_themes: "Tous les thèmes",
    new: "Nouveau",
    box_disclaimer_text: "Comme vous venez de commencer ou que vos boîtes sont vides, nous remplissons la session avec du nouveau vocabulaire. Dès qu'il y aura plus de vocabulaire dans la boîte 2 et plus, nous donnerons automatiquement la priorité aux révisions pour un succès d'apprentissage maximal.",
    learning_activity: "Activité d'apprentissage (7 jours)",
    box_distribution: "Distribution des boîtes",
    correct: "Correct",
    show_details: "Afficher les détails",
    hide_details: "Masquer les détails",
    privacy_policy: "Politique de confidentialité",
    privacy_at_maylang: "Vie privée chez Maylang",
    privacy_intro: "Vos données vous appartiennent. Maylang a été développé pour vous aider à apprendre des langues sans compromettre votre vie privée.",
    privacy_what_save_title: "1. Ce que nous stockons",
    privacy_what_save_desc: "Maylang stocke uniquement les données nécessaires à votre progression. Cela inclut :",
    privacy_item_progress: "Vos listes de vocabulaire et votre état d'apprentissage.",
    privacy_item_history: "Votre historique d'apprentissage et vos statistiques.",
    privacy_item_settings: "Vos paramètres d'application.",
    privacy_item_google: "Votre identifiant Google (uniquement avec synchro cloud).",
    privacy_what_save_footer: "Aucune autre donnée personnelle n'est collectée.",
    privacy_location_title: "2. Emplacement et sécurité",
    privacy_location_desc: "Vos données sont stockées localement. Connecté, des snapshots sont sauvegardés sur Google Firebase Storage (Serveur situé aux USA).",
    privacy_duration_title: "3. Durée et suppression",
    privacy_duration_desc: "Données conservées tant que vous avez un compte. Suppression possible via les paramètres.",
    privacy_third_party_title: "4. Partage avec des tiers",
    privacy_third_party_desc: "Pas de partage avec des tiers. Aucun tracking publicitaire.",
    privacy_contact_title: "5. Contact",
    privacy_contact_desc: "Des questions ? Contactez-nous par feedback ou email.",
    privacy_updated: "Mise à jour : Mai 2026",
  },
  ceb: {
    dashboard: "Dashboard",
    learn: "Pagtuon",
    vocabulary: "Bokabularyo",
    settings: "Mga Setting",
    themes: "Mga Tema",
    progress_overview: "Ang imong pag-uswag sa pagkat-on.",
    ready_to_learn: "Andam",
    learned: "Nakatuon",
    archive: "Archive",
    errors: "Mga Sayop",
    daily_goal_vocab: "Tumong: Mga Pulong",
    daily_goal_time: "Tumong: Oras",
    goal_reached: "Naabot ang tumong! 🎉",
    minutes: "Minuto",
    vocab_per_min: "Pulong / Min",
    correct_per_min: "Husto / Min",
    active_words: "Aktibo nga Pulong",
    what_to_learn: "Unsa ang gusto nimo tun-an karon?",
    start_session: "Sugdi ang Session",
    cancel: "I-cancel",
    save: "I-save",
    language: "Pinulongan",
    ui_language: "Pinulongan sa App",
    select_language: "Pilia ang pinulongan sa interface",
    german: "German",
    english: "Ingles",
    french: "Pranses",
    bisaya: "Bisaya",
    tagalog: "Tagalog",
    session_finished: "Nahuman na ang Session!",
    back_to_dashboard: "Balik sa Dashboard",
    no_vocab_available: "Walay bokabularyo nga magamit",
    session_prep: "Pag-andam sa Session",
    results: "Resulta",
    duration: "Gidugayon",
    cards_processed: "mga kard nga malampusong naproseso",
    manage_vocab_lists: "Pagdumala sa mga Listahan sa Bokabularyo",
    data_management: "Pagdumala sa Data",
    learning_intervals: "Mga Interval sa Pagkat-on",
    feedback_support: "Feedback ug Suporta",
    sources: "Mga Tinubdan",
    settings_and_data: "Mga Setting ug Data",
    answer: "Tubag",
    show_answer: "Ipakita ang Tubag",
    word_type: "Matang sa Pulong",
    article: "Artikulo",
    singular: "Singular",
    plural: "Plural",
    auxiliary_verb: "Auxiliary nga Berbo",
    past_participle: "Past Participle",
    present_tense: "Present (siya)",
    past_tense: "Past (siya)",
    example_sentence: "Pananglitan nga Hugpulong",
    synonyms: "Mga Sinónimo",
    antonyms: "Mga Kaatbang",
    notes: "Mga Nota",
    undo_last_card: "I-undo ang Katapusang Kard",
    end_session_and_save: "Tapusa ang Session ug I-save",
    session_progress_error: "Dili ma-load ang pag-uswag sa session.",
    session_progress_error_hint: "Mahitabo kini sa paspas kaayo nga mga input.",
    progress: "Pag-uswag",
    time_remaining: "Nabilin nga Oras",
    de_en: "German → Ingles",
    en_de: "Ingles → German",
    content_balance: "Sulod ug Balanse",
    vocab_lists: "Mga Listahan sa Bokabularyo",
    clear_all: "I-clear Tanan",
    all_lists: "Tanan nga Listahan",
    select_lists_hint: "Pilia ang usa o daghan pa nga listahan aron tun-an.",
    word_mix: "Word Mix",
    more_review: "Dugang nga Pag-review",
    more_new: "Dugang nga Bag-ong Pulong",
    learning_direction: "Direksyon sa Pagkat-on",
    de_to_en: "German paingon sa Ingles",
    en_to_de: "Ingles paingon sa German",
    mixed: "Sagol",
    random_change: "Random nga Pagbag-o",
    session_goal: "Tumong sa Session",
    how_to_measure: "Giunsa nimo gusto sukdon?",
    measure_hint: "Pilia tali sa usa ka piho nga gidaghanon o usa ka yugto sa oras.",
    card_count: "Gidaghanon sa Kard",
    time_limit: "Limit sa Oras",
    vocab_count: "Mga Pulong",
    recommended: "Girekomendar",
    pro_tip: "Pro Tip:",
    manage_themes: "Pagdumala sa mga Tema",
    select_theme: "Pilia ang Tema",
    all_themes: "Tanan nga Tema",
    new: "Bag-o",
    box_disclaimer_text: "Tungod kay nagsugod pa ka o walay sulod ang imong mga box, gipuno namo ang session og bag-ong bokabularyo. Sa higayon nga duna nay daghang bokabularyo sa Box 2 ug pataas, awtomatiko namong unahon ang mga review para sa labing maayong resulta sa pagkat-on.",
    learning_activity: "Kalihokan sa Pagkat-on (7 ka Adlaw)",
    box_distribution: "Distribusyon sa Box",
    correct: "Husto",
    show_details: "Ipakita ang detalye",
    hide_details: "Itago ang detalye",
    privacy_policy: "Polisiya sa Pribasiya",
    privacy_at_maylang: "Pribasiya sa Maylang",
    privacy_intro: "Imoha ang imong data. Ang Maylang gihimo aron tabangan ka nga makat-on og pinulongan nga dili makompromiso ang imong pribasiya.",
    privacy_what_save_title: "1. Unsay among i-save",
    privacy_item_progress: "Imong mga listahan ug kahimtang sa pagkat-on.",
    privacy_item_history: "Kasaysayan sa pagkat-on ug estadistika.",
    privacy_item_settings: "Setting sa app.",
    privacy_item_google: "Google ID (sync lang).",
    privacy_what_save_footer: "Walay laing personal nga data nga kuhaon.",
    privacy_location_title: "2. Lokasyon ug Siguridad",
    privacy_location_desc: "Lokal nga gi-save ang imong data. Inig login, naay snapshots sa Google Storage (USA).",
    privacy_duration_title: "3. Gidugayon ug Pag-delete",
    privacy_duration_desc: "I-save lang namo samtang duna kay account. Pwede i-delete sa settings.",
    privacy_third_party_title: "4. Pag-share sa uban",
    privacy_third_party_desc: "Dili mi mo-share sa uban. Walay advertising tracking.",
    privacy_contact_title: "5. Kontakt",
    privacy_contact_desc: "Duna kay pangutana? Kontaka mi sa feedback o email.",
    privacy_updated: "Petsa: Mayo 2026",
  },
  tl: {
    dashboard: "Dashboard",
    learn: "Mag-aral",
    vocabulary: "Bokabularyo",
    settings: "Mga Setting",
    themes: "Mga Tema",
    progress_overview: "Ang iyong pag-unlad sa pag-aaral.",
    ready_to_learn: "Handa",
    learned: "Natutunan",
    archive: "Archive",
    errors: "Mga Mali",
    daily_goal_vocab: "Layunin: Mga Salita",
    daily_goal_time: "Layunin: Oras",
    goal_reached: "Naabot ang layunin! 🎉",
    minutes: "Minuto",
    vocab_per_min: "Salita / Min",
    correct_per_min: "Tama / Min",
    active_words: "Aktibong Salita",
    what_to_learn: "Ano ang gusto mong pag-aralan ngayon?",
    start_session: "Simulan ang Session",
    cancel: "I-cancel",
    save: "I-save",
    language: "Wika",
    ui_language: "Wika ng App",
    select_language: "Piliin ang wika ng interface",
    german: "Aleman",
    english: "Ingles",
    french: "Pranses",
    bisaya: "Bisaya",
    tagalog: "Tagalog",
    session_finished: "Tapos na ang Session!",
    back_to_dashboard: "Bumalik sa Dashboard",
    no_vocab_available: "Walay bokabularyo na magagamit",
    session_prep: "Ihanda ang Session",
    results: "Resulta",
    duration: "Tagal",
    cards_processed: "mga card na matagumpay na naproseso",
    manage_vocab_lists: "Pamahalaan ang mga Listahan ng Bokabularyo",
    data_management: "Pamamahala ng Data",
    learning_intervals: "Mga Interval ng Pag-aaral",
    feedback_support: "Feedback at Suporta",
    sources: "Mga Pinagmulan",
    settings_and_data: "Mga Setting at Data",
    answer: "Sagot",
    show_answer: "Ipakita ang Sagot",
    word_type: "Uri ng Salita",
    article: "Artikulo",
    singular: "Singular",
    plural: "Plural",
    auxiliary_verb: "Auxiliary na Pandiwa",
    past_participle: "Past Participle",
    present_tense: "Present (siya)",
    past_tense: "Past (siya)",
    example_sentence: "Halimbawang Pangungusap",
    synonyms: "Mga Kasingkahulugan",
    antonyms: "Mga Kasalungat",
    notes: "Mga Tala",
    undo_last_card: "I-undo ang Huling Card",
    end_session_and_save: "Tapusin ang Session at I-save",
    session_progress_error: "Hindi ma-load ang pag-unlad ng session.",
    session_progress_error_hint: "Maaari itong mangyari sa napakabilis na mga input.",
    progress: "Pag-unlad",
    time_remaining: "Natitirang Oras",
    de_en: "Aleman → Ingles",
    en_de: "Ingles → Aleman",
    content_balance: "Nilalaman at Balanse",
    vocab_lists: "Mga Listahan ng Bokabularyo",
    clear_all: "I-clear Lahat",
    all_lists: "Lahat ng Listahan",
    select_lists_hint: "Pumili ng isa o higit pang listahan para mag-aral.",
    word_mix: "Word Mix",
    more_review: "Higit pang Pag-review",
    more_new: "Higit pang Bagong Salita",
    learning_direction: "Direksyon ng Pag-aaral",
    de_to_en: "Aleman patungong Ingles",
    en_to_de: "Ingles patungong Aleman",
    mixed: "Halo",
    random_change: "Random na Pagbabago",
    session_goal: "Layunin ng Session",
    how_to_measure: "Paano mo gustong sukatin?",
    measure_hint: "Pumili sa pagitan ng isang takdang bilang o isang yugto ng oras.",
    card_count: "Bilang ng Card",
    time_limit: "Limitasyon sa Oras",
    vocab_count: "Mga Salita",
    recommended: "Inirerekomenda",
    pro_tip: "Pro Tip:",
    manage_themes: "Pamahalaan ang mga Tema",
    select_theme: "Pumili ng Tema",
    all_themes: "Lahat ng Tema",
    new: "Bago",
    box_disclaimer_text: "Dahil nagsisimula ka pa lang o walang laman ang iyong mga box, pinupuno namin ang session ng bagong bokabularyo. Sa sandaling mayroon nang mas maraming bokabularyo sa Box 2 at pataas, awtomatiko naming uunahin ang mga review para sa pinakamahusay na resulta ng pag-aaral.",
    learning_activity: "Aktibidad sa Pag-aaral (7 Araw)",
    box_distribution: "Distribusyon ng Box",
    correct: "Tama",
    show_details: "Ipakita ang detalye",
    hide_details: "Itago ang detalye",
    privacy_policy: "Patakaran sa Pribasya",
    privacy_at_maylang: "Pribasya sa Maylang",
    privacy_intro: "Sayo ang iyong data. Ginawa ang Maylang para tulungan kang mag-aral ng wika nang hindi nakokompromiso ang iyong pribasya.",
    privacy_what_save_title: "1. Ano ang aming sini-save",
    privacy_item_progress: "Iyong mga listahan at katayuan sa pag-aaral.",
    privacy_item_history: "Kasaysayan ng pag-aaral at istatistika.",
    privacy_item_settings: "Mga setting ng app.",
    privacy_item_google: "Google ID (para sa sync).",
    privacy_what_save_footer: "Walang ibang personal na data ang kinukuha.",
    privacy_location_title: "2. Lokasyon at Seguridad",
    privacy_location_desc: "Lokal na sini-save ang data. Kapag naka-login, may snapshots sa Google Storage (USA).",
    privacy_duration_title: "3. Tagal at Pag-delete",
    privacy_duration_desc: "Sini-save lang namin hangga't may account ka. Pwedeng i-delete sa settings.",
    privacy_third_party_title: "4. Pagbabahagi sa Iba",
    privacy_third_party_desc: "Hindi kami nagbabahagi sa iba. Walang advertising tracking.",
    privacy_contact_title: "5. Kontakt",
    privacy_contact_desc: "May mga tanong? Kontakin kami sa feedback o email.",
    privacy_updated: "Petsa: Mayo 2026",
  }
};
